version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: '$(npm bin)/greenkeeper-lockfile-update && $(npm bin)/greenkeeper-lockfile-upload'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ checksum ".circle-sha" }}
  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-repo-{{ checksum ".circle-sha" }}
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-repo-{{ checksum ".circle-sha" }}
      - run: npm test -- --coverage
      - save_cache:
          paths:
            - coverage
          key: v1-coverage-{{ checksum ".circle-sha" }}
  codecov:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
          - v1-coverage-{{ checksum ".circle-sha" }}
      - run: $(npm bin)/codecov
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-repo-{{ checksum ".circle-sha" }}
      - run: npm run semantic-release || true

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - codecov:
          requires:
            - test
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
