defaults: &defaults
  docker:
    - image: circleci/node:9
  working_directory: ~/repo

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create package-lock.json checksum
          command: sha256sum package-lock.json > .package-lock-sum
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".package-lock-sum" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: 'Update lockfile'
          command: '$(npm bin)/greenkeeper-lockfile-update && $(npm bin)/greenkeeper-lockfile-upload'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".package-lock-sum" }}
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Revision }}
  lint:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Lint
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Run unit tests
          command: npm test -- --coverage
      - save_cache:
          paths:
            - coverage
          key: v1-coverage-{{ .Revision }}
  codecov:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - restore_cache:
          keys:
          - v1-coverage-{{ .Revision }}
      - run:
          name: Upload coverage
          command: $(npm bin)/codecov
  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-repo-{{ .Revision }}
      - run:
          name: Release
          command: npm run semantic-release || true

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - codecov:
          requires:
            - test
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
